#!/usr/bin/env bun
import { cp, mkdir, readFile, rm, stat, writeFile } from "node:fs/promises"
import { homedir } from "node:os"
import { dirname, resolve } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"

const managedMarker = "semantic-search amp installer managed"

type InstallScope = "system" | "workspace"

interface InstallOptions {
  readonly scope: InstallScope
  readonly force: boolean
  readonly workspaceRoot: string
}

const usage = `Install the semantic-search Amp plugin and skill.

Usage:
  bun run amp:install [-- --system|--workspace] [--workspace-root <path>] [--force]

Options:
  --system          Install user-wide into ~/.config/amp/plugins and ~/.config/agents/skills (default).
  --workspace       Install into <workspace>/.amp/plugins and <workspace>/.agents/skills.
  --workspace-root  Workspace path for --workspace installs (default: current directory).
  --force           Overwrite an existing non-semantic-search plugin or skill with the same name.
  --help            Show this help.
`

const isErrno = (error: unknown): error is NodeJS.ErrnoException =>
  typeof error === "object" && error !== null && "code" in error

const parseArgs = (args: ReadonlyArray<string>): InstallOptions => {
  let scope: InstallScope = "system"
  let force = false
  let workspaceRoot = process.cwd()

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index]
    if (arg === "--system" || arg === "--global") {
      scope = "system"
      continue
    }
    if (arg === "--workspace") {
      scope = "workspace"
      continue
    }
    if (arg === "--workspace-root") {
      const next = args[index + 1]
      if (!next) throw new Error("--workspace-root requires a path")
      workspaceRoot = resolve(next)
      index += 1
      continue
    }
    if (arg === "--force") {
      force = true
      continue
    }
    if (arg === "--help" || arg === "-h") {
      console.log(usage)
      process.exit(0)
    }
    throw new Error(`Unknown argument: ${arg}\n\n${usage}`)
  }

  return { scope, force, workspaceRoot: resolve(workspaceRoot) }
}

const readIfExists = async (file: string): Promise<string | undefined> => {
  try {
    return await readFile(file, "utf8")
  } catch (error) {
    if (isErrno(error) && error.code === "ENOENT") return undefined
    throw error
  }
}

const assertManagedOrMissing = async (file: string, force: boolean, label: string) => {
  const existing = await readIfExists(file)
  if (existing === undefined || existing.includes(managedMarker) || force) return
  throw new Error(`${label} already exists and was not created by semantic-search: ${file}\nUse --force to overwrite it.`)
}

const sourceRoot = (): string => resolve(fileURLToPath(new URL("../../", import.meta.url)))

const install = async (options: InstallOptions) => {
  const root = sourceRoot()
  const sourcePlugin = resolve(root, "src/amp/plugin.ts")
  const sourceSkill = resolve(root, "src/amp/skills/searching-code")
  await Promise.all([stat(sourcePlugin), stat(sourceSkill)])

  const pluginDir =
    options.scope === "system"
      ? resolve(homedir(), ".config/amp/plugins")
      : resolve(options.workspaceRoot, ".amp/plugins")
  const skillRoot =
    options.scope === "system"
      ? resolve(homedir(), ".config/agents/skills")
      : resolve(options.workspaceRoot, ".agents/skills")
  const pluginFile = resolve(pluginDir, "semantic-search.ts")
  const skillDir = resolve(skillRoot, "searching-code")
  const skillFile = resolve(skillDir, "SKILL.md")

  await assertManagedOrMissing(pluginFile, options.force, "Amp plugin")
  await assertManagedOrMissing(skillFile, options.force, "Amp skill")
  await Promise.all([mkdir(dirname(pluginFile), { recursive: true }), mkdir(skillRoot, { recursive: true })])

  const sourcePluginUrl = pathToFileURL(sourcePlugin).href
  await writeFile(
    pluginFile,
    [
      `// ${managedMarker}`,
      "// Generated by semantic-search. Re-run `bun run amp:install` after moving this checkout.",
      `// Source: ${sourcePlugin}`,
      `export { default } from ${JSON.stringify(sourcePluginUrl)}`,
      ""
    ].join("\n")
  )

  await rm(skillDir, { recursive: true, force: true })
  await cp(sourceSkill, skillDir, { recursive: true })

  console.log(`Installed semantic-search Amp integration (${options.scope}):`)
  console.log(`- plugin: ${pluginFile}`)
  console.log(`- skill:  ${skillDir}`)
  console.log("Restart Amp or run `plugins: reload` from the command palette.")
}

install(parseArgs(process.argv.slice(2))).catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exitCode = 1
})
